__author__ = 'JK'

from settings import *
import pygame
import os

class Keyhelper():
    def __init__(self):
        pass

    def printKeyInfo(self):
        file = g_log + "keys.log"
        if not os.path.exists(file):
            keyfile = open(file, 'w')
            keyfile.write('Keylist \n')

            keyfile.write(str("K_BACKSPACE        " + str(pygame.K_BACKSPACE) + " , " + str(pygame.key.name(pygame.K_BACKSPACE)) + "\n"))
            keyfile.write(str("K_TAB              " + str(pygame.K_TAB) + " , " + str(pygame.key.name(pygame.K_TAB)) + "\n"))
            keyfile.write(str("K_CLEAR            " + str(pygame.K_CLEAR) + " , " + str(pygame.key.name(pygame.K_CLEAR)) + "\n"))
            keyfile.write(str("K_RETURN           " + str(pygame.K_RETURN) + " , " + str(pygame.key.name(pygame.K_RETURN)) + "\n"))
            keyfile.write(str("K_PAUSE            " + str(pygame.K_PAUSE) + " , " + str(pygame.key.name(pygame.K_PAUSE)) + "\n"))
            keyfile.write(str("K_ESCAPE           " + str(pygame.K_ESCAPE) + " , " + str(pygame.key.name(pygame.K_ESCAPE)) + "\n"))
            keyfile.write(str("K_SPACE            " + str(pygame.K_SPACE) + " , " + str(pygame.key.name(pygame.K_SPACE)) + "\n"))
            keyfile.write(str("K_EXCLAIM          " + str(pygame.K_EXCLAIM) + " , " + str(pygame.key.name(pygame.K_EXCLAIM)) + "\n"))
            keyfile.write(str("K_QUOTEDBL         " + str(pygame.K_QUOTEDBL) + " , " + str(pygame.key.name(pygame.K_QUOTEDBL)) + "\n"))
            keyfile.write(str("K_HASH             " + str(pygame.K_HASH) + " , " + str(pygame.key.name(pygame.K_HASH)) + "\n"))
            keyfile.write(str("K_DOLLAR           " + str(pygame.K_DOLLAR) + " , " + str(pygame.key.name(pygame.K_DOLLAR)) + "\n"))
            keyfile.write(str("K_AMPERSAND        " + str(pygame.K_AMPERSAND) + " , " + str(pygame.key.name(pygame.K_AMPERSAND)) + "\n"))
            keyfile.write(str("K_QUOTE            " + str(pygame.K_QUOTE) + " , " + str(pygame.key.name(pygame.K_QUOTE)) + "\n"))
            keyfile.write(str("K_LEFTPAREN        " + str(pygame.K_LEFTPAREN) + " , " + str(pygame.key.name(pygame.K_LEFTPAREN)) + "\n"))
            keyfile.write(str("K_RIGHTPAREN       " + str(pygame.K_RIGHTPAREN) + " , " + str(pygame.key.name(pygame.K_RIGHTPAREN)) + "\n"))
            keyfile.write(str("K_ASTERISK         " + str(pygame.K_ASTERISK) + " , " + str(pygame.key.name(pygame.K_ASTERISK)) + "\n"))
            keyfile.write(str("K_PLUS             " + str(pygame.K_PLUS) + " , " + str(pygame.key.name(pygame.K_PLUS)) + "\n"))
            keyfile.write(str("K_COMMA            " + str(pygame.K_COMMA) + " , " + str(pygame.key.name(pygame.K_COMMA)) + "\n"))
            keyfile.write(str("K_MINUS            " + str(pygame.K_MINUS) + " , " + str(pygame.key.name(pygame.K_MINUS)) + "\n"))
            keyfile.write(str("K_PERIOD           " + str(pygame.K_PERIOD) + " , " + str(pygame.key.name(pygame.K_PERIOD)) + "\n"))
            keyfile.write(str("K_SLASH            " + str(pygame.K_SLASH) + " , " + str(pygame.key.name(pygame.K_SLASH)) + "\n"))
            keyfile.write(str("K_0                " + str(pygame.K_0) + " , " + str(pygame.key.name(pygame.K_0)) + "\n"))
            keyfile.write(str("K_1                " + str(pygame.K_1) + " , " + str(pygame.key.name(pygame.K_1)) + "\n"))
            keyfile.write(str("K_2                " + str(pygame.K_2) + " , " + str(pygame.key.name(pygame.K_2)) + "\n"))
            keyfile.write(str("K_3                " + str(pygame.K_3) + " , " + str(pygame.key.name(pygame.K_3)) + "\n"))
            keyfile.write(str("K_4                " + str(pygame.K_4) + " , " + str(pygame.key.name(pygame.K_4)) + "\n"))
            keyfile.write(str("K_5                " + str(pygame.K_5) + " , " + str(pygame.key.name(pygame.K_5)) + "\n"))
            keyfile.write(str("K_6                " + str(pygame.K_6) + " , " + str(pygame.key.name(pygame.K_6)) + "\n"))
            keyfile.write(str("K_7                " + str(pygame.K_7) + " , " + str(pygame.key.name(pygame.K_7)) + "\n"))
            keyfile.write(str("K_8                " + str(pygame.K_8) + " , " + str(pygame.key.name(pygame.K_8)) + "\n"))
            keyfile.write(str("K_9                " + str(pygame.K_9) + " , " + str(pygame.key.name(pygame.K_9)) + "\n"))
            keyfile.write(str("K_COLON            " + str(pygame.K_COLON) + " , " + str(pygame.key.name(pygame.K_COLON)) + "\n"))
            keyfile.write(str("K_SEMICOLON        " + str(pygame.K_SEMICOLON) + " , " + str(pygame.key.name(pygame.K_SEMICOLON)) + "\n"))
            keyfile.write(str("K_LESS             " + str(pygame.K_LESS) + " , " + str(pygame.key.name(pygame.K_LESS)) + "\n"))
            keyfile.write(str("K_EQUALS           " + str(pygame.K_EQUALS) + " , " + str(pygame.key.name(pygame.K_EQUALS)) + "\n"))
            keyfile.write(str("K_GREATER          " + str(pygame.K_GREATER) + " , " + str(pygame.key.name(pygame.K_GREATER)) + "\n"))
            keyfile.write(str("K_QUESTION         " + str(pygame.K_QUESTION) + " , " + str(pygame.key.name(pygame.K_QUESTION)) + "\n"))
            keyfile.write(str("K_AT               " + str(pygame.K_AT) + " , " + str(pygame.key.name(pygame.K_AT)) + "\n"))
            keyfile.write(str("K_LEFTBRACKET      " + str(pygame.K_LEFTBRACKET) + " , " + str(pygame.key.name(pygame.K_LEFTBRACKET)) + "\n"))
            keyfile.write(str("K_BACKSLASH        " + str(pygame.K_BACKSLASH) + " , " + str(pygame.key.name(pygame.K_BACKSLASH)) + "\n"))
            keyfile.write(str("K_RIGHTBRACKET     " + str(pygame.K_RIGHTBRACKET) + " , " + str(pygame.key.name(pygame.K_RIGHTBRACKET)) + "\n"))
            keyfile.write(str("K_CARET            " + str(pygame.K_CARET) + " , " + str(pygame.key.name(pygame.K_CARET)) + "\n"))
            keyfile.write(str("K_UNDERSCORE       " + str(pygame.K_UNDERSCORE) + " , " + str(pygame.key.name(pygame.K_UNDERSCORE)) + "\n"))
            keyfile.write(str("K_BACKQUOTE        " + str(pygame.K_BACKQUOTE) + " , " + str(pygame.key.name(pygame.K_BACKQUOTE)) + "\n"))
            keyfile.write(str("K_a                " + str(pygame.K_a) + " , " + str(pygame.key.name(pygame.K_a)) + "\n"))
            keyfile.write(str("K_b                " + str(pygame.K_b) + " , " + str(pygame.key.name(pygame.K_b)) + "\n"))
            keyfile.write(str("K_c                " + str(pygame.K_c) + " , " + str(pygame.key.name(pygame.K_c)) + "\n"))
            keyfile.write(str("K_d                " + str(pygame.K_d) + " , " + str(pygame.key.name(pygame.K_d)) + "\n"))
            keyfile.write(str("K_e                " + str(pygame.K_e) + " , " + str(pygame.key.name(pygame.K_e)) + "\n"))
            keyfile.write(str("K_f                " + str(pygame.K_f) + " , " + str(pygame.key.name(pygame.K_f)) + "\n"))
            keyfile.write(str("K_g                " + str(pygame.K_g) + " , " + str(pygame.key.name(pygame.K_g)) + "\n"))
            keyfile.write(str("K_h                " + str(pygame.K_h) + " , " + str(pygame.key.name(pygame.K_h)) + "\n"))
            keyfile.write(str("K_i                " + str(pygame.K_i) + " , " + str(pygame.key.name(pygame.K_i)) + "\n"))
            keyfile.write(str("K_j                " + str(pygame.K_j) + " , " + str(pygame.key.name(pygame.K_j)) + "\n"))
            keyfile.write(str("K_k                " + str(pygame.K_k) + " , " + str(pygame.key.name(pygame.K_k)) + "\n"))
            keyfile.write(str("K_l                " + str(pygame.K_l) + " , " + str(pygame.key.name(pygame.K_l)) + "\n"))
            keyfile.write(str("K_m                " + str(pygame.K_m) + " , " + str(pygame.key.name(pygame.K_m)) + "\n"))
            keyfile.write(str("K_n                " + str(pygame.K_n) + " , " + str(pygame.key.name(pygame.K_n)) + "\n"))
            keyfile.write(str("K_o                " + str(pygame.K_o) + " , " + str(pygame.key.name(pygame.K_o)) + "\n"))
            keyfile.write(str("K_p                " + str(pygame.K_p) + " , " + str(pygame.key.name(pygame.K_p)) + "\n"))
            keyfile.write(str("K_q                " + str(pygame.K_q) + " , " + str(pygame.key.name(pygame.K_q)) + "\n"))
            keyfile.write(str("K_r                " + str(pygame.K_r) + " , " + str(pygame.key.name(pygame.K_r)) + "\n"))
            keyfile.write(str("K_s                " + str(pygame.K_s) + " , " + str(pygame.key.name(pygame.K_s)) + "\n"))
            keyfile.write(str("K_t                " + str(pygame.K_t) + " , " + str(pygame.key.name(pygame.K_t)) + "\n"))
            keyfile.write(str("K_u                " + str(pygame.K_u) + " , " + str(pygame.key.name(pygame.K_u)) + "\n"))
            keyfile.write(str("K_v                " + str(pygame.K_v) + " , " + str(pygame.key.name(pygame.K_v)) + "\n"))
            keyfile.write(str("K_w                " + str(pygame.K_w) + " , " + str(pygame.key.name(pygame.K_w)) + "\n"))
            keyfile.write(str("K_x                " + str(pygame.K_x) + " , " + str(pygame.key.name(pygame.K_x)) + "\n"))
            keyfile.write(str("K_y                " + str(pygame.K_y) + " , " + str(pygame.key.name(pygame.K_y)) + "\n"))
            keyfile.write(str("K_z                " + str(pygame.K_z) + " , " + str(pygame.key.name(pygame.K_z)) + "\n"))
            keyfile.write(str("K_DELETE           " + str(pygame.K_DELETE) + " , " + str(pygame.key.name(pygame.K_DELETE)) + "\n"))
            keyfile.write(str("K_KP0              " + str(pygame.K_KP0) + " , " + str(pygame.key.name(pygame.K_KP0)) + "\n"))
            keyfile.write(str("K_KP1              " + str(pygame.K_KP1) + " , " + str(pygame.key.name(pygame.K_KP1)) + "\n"))
            keyfile.write(str("K_KP2              " + str(pygame.K_KP2) + " , " + str(pygame.key.name(pygame.K_KP2)) + "\n"))
            keyfile.write(str("K_KP3              " + str(pygame.K_KP3) + " , " + str(pygame.key.name(pygame.K_KP3)) + "\n"))
            keyfile.write(str("K_KP4              " + str(pygame.K_KP4) + " , " + str(pygame.key.name(pygame.K_KP4)) + "\n"))
            keyfile.write(str("K_KP5              " + str(pygame.K_KP5) + " , " + str(pygame.key.name(pygame.K_KP5)) + "\n"))
            keyfile.write(str("K_KP6              " + str(pygame.K_KP6) + " , " + str(pygame.key.name(pygame.K_KP6)) + "\n"))
            keyfile.write(str("K_KP7              " + str(pygame.K_KP7) + " , " + str(pygame.key.name(pygame.K_KP7)) + "\n"))
            keyfile.write(str("K_KP8              " + str(pygame.K_KP8) + " , " + str(pygame.key.name(pygame.K_KP8)) + "\n"))
            keyfile.write(str("K_KP9              " + str(pygame.K_KP9) + " , " + str(pygame.key.name(pygame.K_KP9)) + "\n"))
            keyfile.write(str("K_KP_PERIOD        " + str(pygame.K_KP_PERIOD) + " , " + str(pygame.key.name(pygame.K_KP_PERIOD)) + "\n"))
            keyfile.write(str("K_KP_DIVIDE        " + str(pygame.K_KP_DIVIDE) + " , " + str(pygame.key.name(pygame.K_KP_DIVIDE)) + "\n"))
            keyfile.write(str("K_KP_MULTIPLY      " + str(pygame.K_KP_MULTIPLY) + " , " + str(pygame.key.name(pygame.K_KP_MULTIPLY)) + "\n"))
            keyfile.write(str("K_KP_MINUS         " + str(pygame.K_KP_MINUS) + " , " + str(pygame.key.name(pygame.K_KP_MINUS)) + "\n"))
            keyfile.write(str("K_KP_PLUS          " + str(pygame.K_KP_PLUS) + " , " + str(pygame.key.name(pygame.K_KP_PLUS)) + "\n"))
            keyfile.write(str("K_KP_ENTER         " + str(pygame.K_KP_ENTER) + " , " + str(pygame.key.name(pygame.K_KP_ENTER)) + "\n"))
            keyfile.write(str("K_KP_EQUALS        " + str(pygame.K_KP_EQUALS) + " , " + str(pygame.key.name(pygame.K_KP_EQUALS)) + "\n"))
            keyfile.write(str("K_UP               " + str(pygame.K_UP) + " , " + str(pygame.key.name(pygame.K_UP)) + "\n"))
            keyfile.write(str("K_DOWN             " + str(pygame.K_DOWN) + " , " + str(pygame.key.name(pygame.K_DOWN)) + "\n"))
            keyfile.write(str("K_RIGHT            " + str(pygame.K_RIGHT) + " , " + str(pygame.key.name(pygame.K_RIGHT)) + "\n"))
            keyfile.write(str("K_LEFT             " + str(pygame.K_LEFT) + " , " + str(pygame.key.name(pygame.K_LEFT)) + "\n"))
            keyfile.write(str("K_INSERT           " + str(pygame.K_INSERT) + " , " + str(pygame.key.name(pygame.K_INSERT)) + "\n"))
            keyfile.write(str("K_HOME             " + str(pygame.K_HOME) + " , " + str(pygame.key.name(pygame.K_HOME)) + "\n"))
            keyfile.write(str("K_END              " + str(pygame.K_END) + " , " + str(pygame.key.name(pygame.K_END)) + "\n"))
            keyfile.write(str("K_PAGEUP           " + str(pygame.K_PAGEUP) + " , " + str(pygame.key.name(pygame.K_PAGEUP)) + "\n"))
            keyfile.write(str("K_PAGEDOWN         " + str(pygame.K_PAGEDOWN) + " , " + str(pygame.key.name(pygame.K_PAGEDOWN)) + "\n"))
            keyfile.write(str("K_F1               " + str(pygame.K_F1) + " , " + str(pygame.key.name(pygame.K_F1)) + "\n"))
            keyfile.write(str("K_F2               " + str(pygame.K_F2) + " , " + str(pygame.key.name(pygame.K_F2)) + "\n"))
            keyfile.write(str("K_F3               " + str(pygame.K_F3) + " , " + str(pygame.key.name(pygame.K_F3)) + "\n"))
            keyfile.write(str("K_F4               " + str(pygame.K_F4) + " , " + str(pygame.key.name(pygame.K_F4)) + "\n"))
            keyfile.write(str("K_F5               " + str(pygame.K_F5) + " , " + str(pygame.key.name(pygame.K_F5)) + "\n"))
            keyfile.write(str("K_F6               " + str(pygame.K_F6) + " , " + str(pygame.key.name(pygame.K_F6)) + "\n"))
            keyfile.write(str("K_F7               " + str(pygame.K_F7) + " , " + str(pygame.key.name(pygame.K_F7)) + "\n"))
            keyfile.write(str("K_F8               " + str(pygame.K_F8) + " , " + str(pygame.key.name(pygame.K_F8)) + "\n"))
            keyfile.write(str("K_F9               " + str(pygame.K_F9) + " , " + str(pygame.key.name(pygame.K_F9)) + "\n"))
            keyfile.write(str("K_F10              " + str(pygame.K_F10) + " , " + str(pygame.key.name(pygame.K_F10)) + "\n"))
            keyfile.write(str("K_F11              " + str(pygame.K_F11) + " , " + str(pygame.key.name(pygame.K_F11)) + "\n"))
            keyfile.write(str("K_F12              " + str(pygame.K_F12) + " , " + str(pygame.key.name(pygame.K_F12)) + "\n"))
            keyfile.write(str("K_F13              " + str(pygame.K_F13) + " , " + str(pygame.key.name(pygame.K_F13)) + "\n"))
            keyfile.write(str("K_F14              " + str(pygame.K_F14) + " , " + str(pygame.key.name(pygame.K_F14)) + "\n"))
            keyfile.write(str("K_F15              " + str(pygame.K_F15) + " , " + str(pygame.key.name(pygame.K_F15)) + "\n"))
            keyfile.write(str("K_NUMLOCK          " + str(pygame.K_NUMLOCK) + " , " + str(pygame.key.name(pygame.K_NUMLOCK)) + "\n"))
            keyfile.write(str("K_CAPSLOCK         " + str(pygame.K_CAPSLOCK) + " , " + str(pygame.key.name(pygame.K_CAPSLOCK)) + "\n"))
            keyfile.write(str("K_SCROLLOCK        " + str(pygame.K_SCROLLOCK) + " , " + str(pygame.key.name(pygame.K_SCROLLOCK)) + "\n"))
            keyfile.write(str("K_RSHIFT           " + str(pygame.K_RSHIFT) + " , " + str(pygame.key.name(pygame.K_RSHIFT)) + "\n"))
            keyfile.write(str("K_LSHIFT           " + str(pygame.K_LSHIFT) + " , " + str(pygame.key.name(pygame.K_LSHIFT)) + "\n"))
            keyfile.write(str("K_RCTRL            " + str(pygame.K_RCTRL) + " , " + str(pygame.key.name(pygame.K_RCTRL)) + "\n"))
            keyfile.write(str("K_LCTRL            " + str(pygame.K_LCTRL) + " , " + str(pygame.key.name(pygame.K_LCTRL)) + "\n"))
            keyfile.write(str("K_RALT             " + str(pygame.K_RALT) + " , " + str(pygame.key.name(pygame.K_RALT)) + "\n"))
            keyfile.write(str("K_LALT             " + str(pygame.K_LALT) + " , " + str(pygame.key.name(pygame.K_LALT)) + "\n"))
            keyfile.write(str("K_RMETA            " + str(pygame.K_RMETA) + " , " + str(pygame.key.name(pygame.K_RMETA)) + "\n"))
            keyfile.write(str("K_LMETA            " + str(pygame.K_LMETA) + " , " + str(pygame.key.name(pygame.K_LMETA)) + "\n"))
            keyfile.write(str("K_LSUPER           " + str(pygame.K_LSUPER) + " , " + str(pygame.key.name(pygame.K_LSUPER)) + "\n"))
            keyfile.write(str("K_RSUPER           " + str(pygame.K_RSUPER) + " , " + str(pygame.key.name(pygame.K_RSUPER)) + "\n"))
            keyfile.write(str("K_MODE             " + str(pygame.K_MODE) + " , " + str(pygame.key.name(pygame.K_MODE)) + "\n"))
            keyfile.write(str("K_HELP             " + str(pygame.K_HELP) + " , " + str(pygame.key.name(pygame.K_HELP)) + "\n"))
            keyfile.write(str("K_PRINT            " + str(pygame.K_PRINT) + " , " + str(pygame.key.name(pygame.K_PRINT)) + "\n"))
            keyfile.write(str("K_SYSREQ           " + str(pygame.K_SYSREQ) + " , " + str(pygame.key.name(pygame.K_SYSREQ)) + "\n"))
            keyfile.write(str("K_BREAK            " + str(pygame.K_BREAK) + " , " + str(pygame.key.name(pygame.K_BREAK)) + "\n"))
            keyfile.write(str("K_MENU             " + str(pygame.K_MENU) + " , " + str(pygame.key.name(pygame.K_MENU)) + "\n"))
            keyfile.write(str("K_POWER            " + str(pygame.K_POWER) + " , " + str(pygame.key.name(pygame.K_POWER)) + "\n"))
            keyfile.write(str("K_EURO             " + str(pygame.K_EURO) + " , " + str(pygame.key.name(pygame.K_EURO)) + "\n"))
            keyfile.close()